"""添加dody_html

Revision ID: 39305f9865e5
Revises: f993dc7bd5c5
Create Date: 2019-08-12 15:27:26.818161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39305f9865e5'
down_revision = 'f993dc7bd5c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
